// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvsmkymplknndnmxslbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2c21reW1wbGtubmRubXhzbGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjgwMjgsImV4cCI6MjA2NDUwNDAyOH0.1utlKJRBGhpilut2B6Cq1BP29eSihiztXAvepa9bIQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);